### ISSUE TITLE
Can I use the 3.8.13 tag for a beaglebone black?

### ISSUE THREAD

**Issue by Apromixately** [RobertCNelson/linux-stable-rcn-ee#2]
I have a Beaglebone black running Linux beaglebone 3.8.13-bone79 #1 SMP Tue Oct 13 20:44:55 UTC 2015 armv7l GNU/Linux
Can I use the 3.8.13 tag from this repository to build kernel modules for my board or will they be incompatible?

**Comment by RobertCNelson** [comment]
Use the 3.8.13-bone79 tag
