### ISSUE TITLE
Make error on pcie-designware-host.c

### ISSUE THREAD

**Issue by enginkuzu** [RobertCNelson/linux-stable-rcn-ee#3]
On tag 4.14.108-ti-xenomai-r127, i use custom kernel configuration and i get this compile error : 

`  CC      drivers/pci/dwc/pcie-designware-host.o`
`drivers/pci/dwc/pcie-designware-host.c: In function ‘dw_pcie_host_init’:`
`drivers/pci/dwc/pcie-designware-host.c:408:10: error: too many arguments to function ‘pp->ops->msi_host_init’`
`  408 |    ret = pp->ops->msi_host_init(pp, &dw_pcie_msi_chip);`
`      |          ^~`
`make[2]: *** [scripts/Makefile.build:327: drivers/pci/dwc/pcie-designware-host.o] Error 1`
`make[1]: *** [scripts/Makefile.build:585: drivers/pci/dwc] Error 2`
`make: *** [Makefile:1039: drivers] Error 2`

**Comment by RobertCNelson** [comment]
@enginkuzu sorry, I don't support the Xenomai builds.

Regards,
