### ISSUE TITLE
some dtbs for sancloud bb-enhanced missing

### ISSUE THREAD

**Issue by az143** [RobertCNelson/linux-stable-rcn-ee#4]
the kernel package does not include am335x-sancloud-bbe-uboot-univ.dtb and am335x-sancloud-bbe-uboot.dtb.
(the corresponding files for the more generic bbb/bbb-wireless's are present, ie. am335x-boneblack-uboot-univ.dtb, am335x-boneblack-uboot.dtb)

without am335x-sancloud-bbe-uboot-univ.dtb u-boot (at least all the 2019 versions that i've been looking at) fails to load any overlay for universal cape support if and only if you have any uboot_overlay_addrN in your uEnv.txt. if you have no 
uboot_overlay_addr lines then u-boot correctly falls back to loading one of the univ-bbb-whatever.dtbo files.
(reason for this misbehaviour: uboot_overlay_addrN things are loaded using the capeloadoverlay function, which sets 
cape_uboot which deeply inside uname_boot mistriggers the logic for external capes, prints "uboot_overlays: cape universal disabled, external cape enabled or detected" and disables looking for univ-bbb-whatever.)

i'd say the root cause is that these files aren't included, because on a bbb or a bbb-wireless with the same kernel package, uboot and  uEnv.txt it loads a few addon overlays and enables cape universal without problems.

**Comment by RobertCNelson** [comment]
in progress ;)
